language: node_js
node_js:
  - "8"
sudo: false
node_js:
  - 6.11.1
env:
  - NODE_ENV="test"
before_script:
  - yarn db:setup:user
  - yarn db:reset
script:
  - npm test
  - npm run lint
  - yarn test
  - yarn enforce
  - yarn lint
